In [1]:
#Recall that the hyperbolic sine, denoted by sinh, is exp (x)−exp (−x)
#Write a function my_sinh(x)
#where the output y is the hyperbolic sine computed on x. 
#Assume that x is a 1 by 1 float.
def my_sinh(x):
    import math, numpy
    y = math.sinh(x)
    print(y)

my_sinh(0)
my_sinh(1)
my_sinh(2)

0.0
1.1752011936438014
3.6268604078470186


In [ ]:
#Write a function my_checker_board(n) where the output m is an n × n array 
#with the following form:
#m =
#10101
#01010
#10101
#01010
#10101
#Note that the upper-left element should always be 1. 
#Assume that n is a strictly positive integer. 





In [30]:
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[::2,1::2] = 1
x[1::2,::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [35]:
import numpy as np
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [39]:
print(x[::2])
print(x[1::2])
print("''''''")
print(x[::3])
print("''''''")
print(x[1::2,::2])
print(x[::2,1::2])

[[1 2 3]
 [7 8 9]]
[[ 4  5  6]
 [10 11 12]]
''''''
[[ 1  2  3]
 [10 11 12]]
''''''
[[ 4  6]
 [10 12]]
[[2]
 [8]]


In [34]:
import numpy as np 
def printcheckboard(n): 
    final = [] 
    for i in range(n): 
        final.append(list(np.tile([1,0],int(n/2))) if i%2==0 else list(np.tile([0,1],int(n/2)))) 
    print(np.array(final)) 
  
  
# driver code 
n = 3
printcheckboard(n)

[[1 0]
 [0 1]
 [1 0]]
